# Generated by Django 4.2.3 on 2023-09-27 10:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='заголовок')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('body', models.TextField(verbose_name='содержание')),
                ('preview_img', models.ImageField(blank=True, null=True, upload_to='blogs/', verbose_name='изображение превью')),
                ('date_create', models.DateField(default=django.utils.timezone.now, verbose_name='дата создания')),
                ('is_published', models.BooleanField(default=True, verbose_name='опубликован')),
                ('views_count', models.IntegerField(default=0, verbose_name='просмотры')),
            ],
            options={
                'verbose_name': 'статья',
                'verbose_name_plural': 'статьи',
                'ordering': ('pk',),
            },
        ),
    ]
