# Generated by Django 4.2.4 on 2023-08-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformmessage',
            name='data_sent',
            field=models.CharField(max_length=30, verbose_name='дата сообщения'),
        ),
    ]
